-------------
ASSIGNMENT-2
-------------
Q1
SELECT Name FROM CLIENT_MASTER WHERE Name LIKE '_a%';

Q2
SELECT * FROM CLIENT_MASTER WHERE City LIKE '_a%';

Q3
SELECT * FROM CLIENT_MASTER WHERE City IN ('Bombay', 'Delhi');

Q4
SELECT * FROM CLIENT_MASTER WHERE BalanceDue > 10000;

Q5
SELECT * FROM SALES_ORDER WHERE EXTRACT(month FROM OrderDate) = 1;

Q6
SELECT * FROM SALES_ORDER WHERE ClientNo IN ('C00001', 'C00002');

Q7
SELECT * FROM PRODUCT_MASTER WHERE (SellPrice > 2000 AND SellPrice <= 5000);

Q8
SELECT * FROM PRODUCT_MASTER WHERE SellPrice > 1500;

SELECT SellPrice * 0.15 AS "new_price" FROM PRODUCT_MASTER;

Q9
SELECT Name, City, State FROM CLIENT_MASTER WHERE State <> 'Maharashtra';

Q10
SELECT COUNT(OrderNo) FROM SALES_ORDER;

Q11
SELECT AVG(SellPrice) AS "average_price" FROM PRODUCT_MASTER;  

Q12
SELECT MAX(SellPrice) AS "max_price", MIN(SellPrice) AS "min_price" FROM PRODUCT_MASTER;

Q13
SELECT COUNT(SellPrice) FROM PRODUCT_MASTER WHERE SellPrice >= 1500;

Q14
SELECT * FROM PRODUCT_MASTER WHERE QtyInHand < ReorderLvl;

Q15
SELECT OrderNo, OrderDate, ClientNo FROM SALES_ORDER;

--------------
LAB SESSION-3
-------------
1.
UPDATE PRODUCT_MASTER SET Reorderlvl = 80 WHERE Description = 'Shirts';

2.
UPDATE PRODUCT_MASTER SET SellPrice = SellPrice * 1.01;

3.
UPDATE SALESMAN_MASTER SET YtdSales = YtdSales + 35 WHERE SalesmanNo = 'S00003';

4.
UPDATE SALES_ORDER_DETAILS SET QtyDisp = QtyOrdered WHERE ProductRate <= 1000;

5.
UPDATE CLIENT_MASTER SET Pincode = 400001 WHERE City = 'Mumbai';

6.
UPDATE PRODUCT_MASTER SET Reorderlvl = 2 * Reorderlvl;

7.
DELETE FROM SALES_ORDER WHERE OrderStatus = 'cancelled';

8.
DELETE FROM SALESMAN_MASTER;

9.
SELECT * FROM PRODUCT_MASTER WHERE QtyInHand < ReorderLvl;

10.
UPDATE EMP SET MGR = (SELECT EMPNO FROM EMP WHERE ENAME = 'Blake') WHERE ENAME IN ('Smith', 'Adam');
