1)
SELECT 5*8/2-1 FROM DUAL;

2)
SELECT CURRENT_TIMESTAMP FROM DUAL;

3)
SELECT UPPER('m') FROM DUAL;

4)
SELECT SUBSTR('Accounting', 3, 8) FROM DUAL;

5)
SELECT CURRENT_DATE-1 AS YESTERDAY, CURRENT_DATE AS TODAY, CURRENT_DATE+1 AS TOMORROW FROM DUAL;

6) 
SELECT EXTRACT(MONTH FROM SYSDATE) AS MONTH, EXTRACT(YEAR FROM SYSDATE) AS YEAR FROM DUAL;

7)
SELECT SIN(60), COS(60), TAN(60), ABS(-15), SIGN(-63) FROM DUAL;

8)
SELECT CEIL(4.62), FLOOR(4.32), ABS(-6), LOG(2, 4) FROM DUAL;

9)
SELECT SQRT(5) AS ANS FROM DUAL;

10)
SELECT LOWER('IVAN BAYROSS') AS LOWER_CASE FROM DUAL;

11) 
SELECT UPPER('ivan bayross') AS UPPER_CASE FROM DUAL;

12) 
SELECT TO_CHAR(SYSDATE, 'DD/MM/YY') FROM DUAL;

13)
SELECT ROUND(MONTHS_BETWEEN(TO_DATE('02-JUL-01'), TO_DATE('04-JAN-01'))) AS DIFF FROM DUAL;

14)
SELECT ADD_MONTHS(SYSDATE, 5) AS NEW_DATE FROM DUAL;

15)
SELECT ROUND(15.19,1) AS ANS FROM DUAL;
