-------------
LAB SESSION-7
-------------
1.
SELECT ENAME FROM EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP);
2.
SELECT ENAME FROM EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP WHERE JOB = 'Salesman');
3.
SELECT ENAME FROM EMP WHERE SAL = (SELECT MIN(SAL) FROM EMP WHERE JOB = 'Clerk');
4.
SELECT DNAME FROM DEPT WHERE DNO = (SELECT DEPTNO FROM EMP GROUP BY DEPTNO HAVING AVG(SAL) = (SELECT MAX(AVG(SAL)) FROM EMP GROUP BY DEPTNO));
5.
SELECT ENAME FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'Turner');
6.
SELECT ENAME FROM EMP WHERE HIREDATE > (SELECT HIREDATE FROM EMP WHERE ENAME = 'Allen');
7.
SELECT DNAME FROM DEPT WHERE DNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'Ford');
8.
SELECT DNAME FROM DEPT WHERE DNO = (SELECT DEPTNO FROM EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP));
9.
SELECT LOC FROM DEPT WHERE DNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'Smith');
10.
SELECT LOC FROM DEPT WHERE DNO IN (SELECT DEPTNO FROM EMP WHERE JOB = 'Manager');
11.
SELECT COMM FROM EMP WHERE ENAME = 'Martin';
12.
SELECT ENAME FROM EMP WHERE SAL > (SELECT MAX(SAL) FROM EMP WHERE DEPTNO = (SELECT DNO FROM DEPT WHERE LOC = 'Dallas'));
13.
SELECT DNAME FROM DEPT WHERE DNO NOT IN (SELECT DEPTNO FROM EMP);
14.
SELECT ENAME FROM EMP WHERE HIREDATE = (SELECT HIREDATE FROM EMP WHERE ENAME = 'Adams');
15.
SELECT DNAME FROM DEPT WHERE DNO IN (SELECT DEPTNO FROM EMP WHERE COMM IS NOT NULL);
16.
SELECT ENAME FROM EMP O WHERE SAL = (SELECT MIN(SAL) FROM EMP I WHERE I.DEPTNO = O.DEPTNO);
17.
SELECT DNAME FROM DEPT WHERE DNO IN (SELECT DEPTNO FROM EMP GROUP BY DEPTNO HAVING COUNT(ENAME) > 1);
/* or */
SELECT DNAME FROM DEPT O WHERE COUNT( SELECT 1 FROM EMP I WHERE I.DEPTNO = O.DNO ) > 1;
